version: "3.7"

services:
  webui:
    build:
      context: ./webui
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: app_green_01
    labels:
      - traefik.enable=true
      - traefik.http.services.app_green.loadbalancer.server.port=80
      - traefik.http.routers.app_green_01.entrypoints=traefik  
    ports:
    - "80:80"
