version: "3.7"

services:
  webui:
    build:
      context: ./webui
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: traefik-v2.5
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - `pwd`:/etc/traefik_providers
    ports:
    - "80:80"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik_providers/file_provider.yml
